### ISSUE TITLE
Cannot find module '../cordova/metadata/ios_parser'

### ISSUE THREAD

**Issue by gabrielbhs** [tkyaji/cordova-plugin-crypt-file#48]
Dear,

when i build for iOS platform, console shows files being encrypted but in the end fail with that message:

Error: Cannot find module '../cordova/metadata/ios_parser'

Am i doing something wrong?

**Comment by jordanorc** [comment]
Same problem here!

**Comment by spencerevison** [comment]
Also getting this

**Comment by wendellpalazzo** [comment]
Houston we have a problem!!! ;)
Same problem here!

**Comment by GinjiBan** [comment]
It's a problem since the cordova v7 release as it's working fine on 6.5.0.

They decided to refractor some platform specific stuff and removed the ios_parser file.

**Comment by s-s** [comment]
Fixy fix #51

**Comment by tkyaji** [comment]
Merged #51. Thanks for s-s.

**Comment by GinjiBan** [comment]
Shouldn't you upgrade the version number ?

After removing the plugin and installing it again I still got the old code.

**Comment by tkyaji** [comment]
Sorry. I forgot to `npm publish`. Please run `cordova plugin add` again.

**Comment by GinjiBan** [comment]
Awesome, thank you !
